### ISSUE TITLE
Afvalwijzer

### ISSUE THREAD

**Issue by Sarnog** [smarthomejunkie/Home-Assistant-Tutorials#10]
Hello,

Since the update 2022.10 i get an error:

The entity defination format under tamplate: differs from the platform configuration format.

I think it's the old format used in the template sensor. But i don't know how to fix it into the new.
Can you please help me out?

Thanks in advance!

**Comment by Sarnog** [comment]
I hope anybody can help me out...

**Comment by smarthomejunkie** [comment]
This is because you use a templates.yaml and a configuration.yaml that both din be template sensors. If I find the time I will rewrite the code so that it works with a templates.yaml

**Comment by Sarnog** [comment]
> This is because you use a templates.yaml and a configuration.yaml that both din be template sensors. If I find the time I will rewrite the code so that it works with a templates.yaml

Thanks! I'm looking forward to it...

**Comment by smarthomejunkie** [comment]
I've already rewritten it. Will try to update this asap.

**Comment by smarthomejunkie** [comment]
Updates the code so that it works with the new templates.yaml format

**Comment by Sarnog** [comment]
> Updates the code so that it works with the new templates.yaml format

Thank you very much!
