### ISSUE TITLE
Template sensor for low battery

### ISSUE THREAD

**Issue by cowboysdude** [smarthomejunkie/Home-Assistant-Tutorials#12]
Sensor code for low batteries
I don't mind paying for something but the example that you send does not work...

The error I get is:
Missing Property Platform

I'm not a  Home Assistant expert so any help would be appreciated...

**Comment by smarthomejunkie** [comment]
Hi John,
I'm sorry that you experience this. The example that you downloaded does work. There must be something different in the way you pasted the code. Please check the tutorial video on how to get it to work.

By the way, the code is an example of my battery-powered devices. It might be that your devices use different attributes. In that case, you need to change the filter in the code to make sure your entities are included. But the error that you get has nothing to do with this last thing.

Kind regards,
Ed
