### ISSUE TITLE
The embedded YouTube videos on your website seem to be showing an error?

### ISSUE THREAD

**Issue by handcoding** [smarthomejunkie/Home-Assistant-Tutorials#14]
Hi there,

Just to let you know, on [your blog post about the EP1](https://www.smarthomejunkie.net/a-first-look-at-the-everything-presence-lite-amazing/), the embedded YouTube video seems to be showing an error: “Video unavailable. Playback on other websites has been disabled by the video owner.”

<img width="730" alt="Safari - A first look at the Everything Presence Lite  Amazing! - Smart Home Junkie - Tutorials and Information for your Smart Home and Home Assistant - 2023-11 at 13-05-05" src="https://github.com/smarthomejunkie/Home-Assistant-Tutorials/assets/118319/2033bd4e-143a-4673-bac1-2c29ccb6c028">

PS I had tried to send this using the Contact Us form on your website, but it kept getting rejected. 🤷🏻‍♀️

**Comment by smarthomejunkie** [comment]
Thanks!
Just fixed it. For some reason YouTube turns off embedding videos randomly.
I don't really understand why this happens.

Thanks again!
Ed

**Comment by handcoding** [comment]
Happy to help!

And just as a potential related thing, if you try to send the following text using [your contact us page](https://www.smarthomejunkie.net/contact/), your junk filter seems to totally block it? Anyway, that kinda seems like maybe a false positive?

> Hi there,
> 
> Just to let you know, on your blog post about the EP1, the embedded YouTube video seems to be showing an error: “Video unavailable. Playback on other websites has been disabled by the video owner.”
> https://www.smarthomejunkie.net/a-first-look-at-the-everything-presence-lite-amazing/
> 
> Cheers,
> Ashley

**Comment by smarthomejunkie** [comment]
Thanks! I will look into it. I just tested it and had to go twice through
the captcha and then it got sent.

I will look into it. It has probably something to do worth adding a link to
the message.

Kind regards,
Ed

**Comment by handcoding** [comment]
Right on—that sounds good! And thanks again for all your hard work.
