### ISSUE TITLE
Watering solution stopped working after introducing `weather.get_forecast` action

### ISSUE THREAD

**Issue by Krzysztonek** [smarthomejunkie/Home-Assistant-Tutorials#16]
Hi, Ed @smarthomejunkie , 
Unfortunately, for the time being this awesome watering system solution doesn't work. Please, kindly consider making an updated tutorial with `weather.get_forecast` action, since most of the weather forecast sensors and their attributes are not reachable anymore.

**Comment by smarthomejunkie** [comment]
This is fixed in the code that you can download on Ko-Fi. I also mentioned the fix in the description of the video and created a separate video about it.
