### ISSUE TITLE
Error on script

### ISSUE THREAD

**Issue by MichNLGithub** [smarthomejunkie/Home-Assistant-Tutorials#2]
Hi Sir, I found an error when copying the code in configuration.yaml

error:

bad indentation of a mapping entry at line 34, column 3:
      - platform: template
      ^

**Comment by smarthomejunkie** [comment]
Which script exactly? Can you please address the issue to the correct code? It's not addressed to any script now.

**Comment by MichNLGithub** [comment]
I see, Afvalwijzer/config/entries_for_configuration.yaml

and then line 25 in the file of your configuration.yaml

**Comment by smarthomejunkie** [comment]
Fixed. The line before started with a dot which was wrong.

**Comment by MichNLGithub** [comment]
Thanks, sorry for interrupting I’m still learning ; )

**Comment by smarthomejunkie** [comment]
No problem!

Op za 30 jan. 2021 om 17:56 schreef MichNLGithub <notifications@github.com>
