### ISSUE TITLE
Question about the "Check if Garden should be Watered" automation logic

### ISSUE THREAD

**Issue by hillbicks** [smarthomejunkie/Home-Assistant-Tutorials#6]
Hey there,

I'm currently scratching my head a bit looking at the "Check if Garden should be Watered" automation.

Is my understanding correct, that not watering will be started if the temperature is below 15.1 degrees? Looking at the last part of the automation, the helpers are reset if they haven't been watered between 3 and 4 days and the temperature was not above 15.1 degrees. 

Wouldn't it make sense to enhance it and start the watering again after 7 days or so? 

I'm using your automations in node red btw, so thanks for posting your configuration. Really provided a good starting point for me.

**Comment by smarthomejunkie** [comment]
Indeed, if the temperature hasn't been higher than 15 degrees in three days, the whole cycle of three days starts again.
