### ISSUE TITLE
Latest HA update breaks sensor

### ISSUE THREAD

**Issue by dundiffrunt** [smarthomejunkie/Home-Assistant-Tutorials#7]
Hi,

I'm using the sprinkler project for weeks now and so far it really works well and I'm loving it! Thank you for your work!

Since the last update of HA to 2022.7.0 the below error appears and the sensor is unavailable though. Any idea why this happens?

Cheers
Marco

Logger: homeassistant.helpers.template
Source: helpers/template.py:1926 
First occurred: 7. Juli 2022, 10:03:55 (1367 occurrences) 
Last logged: 08:49:20

Template variable error: None has no element 0 when rendering '{%- set totalprecipitation = 0 | float(0) -%} {%- set ns = namespace() -%} {%- set ns.totalprecipitation = 0 -%} {%- for daypart in range(0, 7) -%} {%- set precipitation = state_attr('weather.openweathermap', 'forecast')[daypart].precipitation -%} {%- set precipitation_probability = state_attr('weather.openweathermap', 'forecast')[daypart].precipitation_probability / 100 %} {% if precipitation_probability > 0 -%} {%- set precipitation = precipitation * precipitation_probability -%} {%- endif -%} {%- set ns.totalprecipitation = ns.totalprecipitation + precipitation -%} {%- endfor %} {{ ns.totalprecipitation | float(0) | round(2) }}'

**Comment by smarthomejunkie** [comment]
Thx.
He's, there's a bug in Openweathermap sinds that release. This will be
fixed in 2022.7.1

Kind regards,
Ed

Op vr 8 jul. 2022 om 08:53 schreef dundiffrunt ***@***.***>

**Comment by dundiffrunt** [comment]
Thank you (again) for the fast reply. I'll wait for the new release then...

**Comment by smarthomejunkie** [comment]
I can confirm that version 2022.7.1 fixed the issue.
