### ISSUE TITLE
Afvalwijzer has fault in config file.

### ISSUE THREAD

**Issue by Sarnog** [smarthomejunkie/Home-Assistant-Tutorials#8]
Hello,

At first i want to thank you for all the great instruction video's you make, they where really helpfull for me!
Now i want to install this trash collection integration, but when i copied and pasted all the yaml text, i got an error message:

The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: while scanning for the next token found character '%' that cannot start any token in "/config/integrations/../entities/templates/afvalwijzer.yaml", line 4, column 6

I don't know what the problem is.

As you see, i use packages, so i made a new yaml file with the template sensor in the templates folder. I added the yaml file with the integration sensor into the integrations folder, i added the customize code in the customize.yaml file and the icons in the www/afvalwijzer folder.

**Comment by Sarnog** [comment]
Still no solution?

**Comment by smarthomejunkie** [comment]
I totally missed this one. If you copy the code exactly the way as it’s shown in the example it should work. There might be an issue with your packages that you’ve created.

**Comment by Rick8619** [comment]
Hello,

Also thanks for the instructions video's but can you make a video of this? I think it wil help alot of dutch people. (including me)

Thanks in advance

**Comment by Sarnog** [comment]
> I totally missed this one. If you copy the code exactly the way as it’s shown in the example it should work. There might be an issue with your packages that you’ve created.

I don't know. I use packages for a while now, but sometimes i'm having trouble with where to store the yaml files. I've tried multiple places, but every time i get an error in yaml check. Accept for the way i putted it in now, but then i get an error after reboot about the disfunctioning integration.

**Comment by smarthomejunkie** [comment]
I don’t think I will create a video for this because the majority of audience does not come from the Netherlands.
