### ISSUE TITLE
Name 2nd automation in dashboard is incorrect in my opinion.

### ISSUE THREAD

**Issue by stefbex** [smarthomejunkie/Home-Assistant-Tutorials#9]
Hi Ed,
Great job, Really love what you made.

I'm quite new to HASS, so I might be mistaken. 
But I think there is a small mistake in the YAML for the dashboard.
The name of the 2nd automation should be:"Sprinkler: Check if Garden Should be Watered"
not "sprinkler_water_the_garden" (that's the script yo created).

All the best.

**Comment by smarthomejunkie** [comment]
Thx. That might be true. When I created my automations, I changed the names, but the entity_id of the automation seems to stay the old entity_id. At my end, it works like it's in Github. I will check if I can change the entity id and fix it in Github if needed.
